# Generated by Django 2.0.3 on 2018-03-25 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deuces_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deucer',
            name='password',
        ),
        migrations.RemoveField(
            model_name='deucer',
            name='username',
        ),
    ]
